### ISSUE TITLE
Create multiple skins

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#10]
So, the skins are now PHP-enabled. You can use `get_cc_data($key)` and `the_cc_data($key)` to get OpenGraph data and `the_cc_target()` to insert `target="_blank"` if it was turned on via settings / shortcode arguments.

Also, the skins are now autodetected via a header in the CSS file (not unlike plugins/themes in WordPress). The only required and used value at the moment is `Skin Name`.

**v1.0.0**
- [x] Generic Light
- [x] Generic Dark

**Future releases**
- [ ] Twenty Sixteen
- [ ] Twenty Fifteen
- [ ] Twenty Fourteen
- [ ] Twenty Thirteen
- [ ] Twenty Twelve
- [ ] Twenty Eleven
- [ ] Twenty Ten

**Comment by khromov** [comment]
@ideag A question regarding the theme system, what is the purpose of `$type` in `_get_file()` ? 

From what I can see, the main template is `content-cards.php`, what is `content-cards-website.php` used for?

**Comment by ideag** [comment]
@khromov OpenGraph protocol allows you to set `type` (`og:type`) of your link (`website`, `article`, `video`, etc.) and we might want to have different templates for different types of content. `content-cards.php` is the default, catch-all template, and `content-cards-website.php` is an example of how to setup a different template for `og:type=website` links. At the moment the actual templates are the same, and the second template exists just to prove the concept.

**Comment by khromov** [comment]
@ideag Good to know!

Working on the "fancy" templates now. :smile:
