### ISSUE TITLE
Can I fork this repo? LICENSE?

### ISSUE THREAD

**Issue by ash-r1** [ideag/content-cards#110]
Hi, I'm considering giving a tiny update for this plugin. (just follow the latest wp)
But, I'm not sure is it okay to fork this repository, because the license is ambiguous.

If Mr. @ideag feels okay, please put the LICENSE file, I feel GPL is fine because WP itself is GPL. Or, MIT is great of course.

And also, is anyone's touching this repo still? Can I send a Pull Request?

**Comment by khromov** [comment]
@ash-r1 Hey Ash! This plugin is GPL (v2), it's a [requirement for inclusion on WordPress.org](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#1-plugins-must-be-compatible-with-the-gnu-general-public-license). It's stated in multiple places like `readme.txt` and in the plugin header.

You are welcome to fork and exercise all freedoms. 😄

**Comment by ash-r1** [comment]
@khromov oops, readme says that. I've checked github's license feature only (based on `LICENSE.txt`-ish file )

Anyways, thank you for your quick reply! 🙇
