### ISSUE TITLE
Validation and template functions

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#15]
Right now we're using esc_url() for some variables in the template functions, I propose instead that we create dedicated functions that are escaped properly ahead of time:

```
the_cc_url();
the_cc_title();
the_cc_description();
the_cc_site_name();
the_cc_domain(); //New suggestion! Example: domain.com, like Facebook does it
```

These would also need to have versions starting with `get_` as well.

It would imho simplify templating quite a bit.

**Comment by ideag** [comment]
Hmm, I guess we could add some more common data bits as separate functions. Or, we could add a second argument to `the_cc_data($key,$escape)` as a flag to show if we want to escape or not. I would probably advocate for not cluttering global namespace with a lot of different functions, but I'd probably make an exception for `the_cc_image()/get_cc_image()`, especially if we have plans, to cache images later in the roadmap.

**Comment by khromov** [comment]
We could add an escape flag, but some values use different escaping function.

For example, `the_cc_url()` would use `esc_url()` while `the_cc_image()` should probably use `esc_html()`.

We could do something similar to what you proposed instead, and pass the name of the validation function as the second parameter, ie: `the_cc_data('image', 'esc_html');`

I've done a snippet similar to that in this post, if you check out the `get_field_escaped()` function example:
http://snippets.khromov.se/sanitizing-and-securing-advanced-custom-fields-output/

**Comment by ideag** [comment]
Agreed with passing validation function rather than just a flag
