### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#19]
Before this moves much forward, I'd like to rename the repo to `ideag/content-cards` to mirror the name on the WP.org repo.

**Comment by khromov** [comment]
Agreed! Let's do shortly before publishing the first version on WP.org? :+1:

**Comment by lincourtl** [comment]
Content Cards is a great name! :+1:

**Comment by ideag** [comment]
@khromov ok, will change it the same day we release.
@lincourtl thanks! :)
