### ISSUE TITLE
Loading icon for dark theme

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#32]
Right now, the light theme loading gif is always used. We need to make a separate dark gif that matches the dark color schemes, add in the proper filters etc.

**Comment by ideag** [comment]
@khromov I am not convinced the loading screen should adhere to card skin settings. It is used exclusively in WP editor, so I think we should focus to styling it consistently to WP Admin instead.

**Comment by khromov** [comment]
@ideag Many themes inject their styles into the TinyMCE editor to better match the themes appearance. It sets an expectation for the user, and since content cards are currently styled the same way in TinyMCE as on the frontend, I'm not sure it's a great idea to separate the two. :cry:

**Comment by ideag** [comment]
Ok, you convinced me on that one :)
