### ISSUE TITLE
Text wrapping inconsistent on Twenty Fifteen

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#33]
Sometimes the text in the default skin goes outside the Content Card box on the frontend on Twenty Fifteen.

**Comment by khromov** [comment]
Still working on resolving this....

**Comment by ideag** [comment]
Any progress on this, @khromov ?

**Comment by khromov** [comment]
No, the reflow issue is really weird. I've asked a frontend ninja for some advice,  will report back asap.

**Comment by ideag** [comment]
**Update**. @khromov I think this is not specific to Content Cards, I just noticed similar behavior with a div from another plugin I am working with. I think this might be happening if external font takes a long time to load. The page renders boxes with smaller texts, and after the font is finally loaded, the block level elements fail to re-size accordingly.

**Comment by ideag** [comment]
@khromov any progress on this from your end?

**Comment by ideag** [comment]
@khromov so, is this a `wontfix` ?

**Comment by khromov** [comment]
@ideag Unfortunately I think so. It was a minor issue anyway and might have been a browser quirk. We should check Twenty Seventeen compatibility, I started a ticket in #89

**Comment by ideag** [comment]
Alright, closing this as wontfix
