### ISSUE TITLE
Better image handling

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#40]
From AWP post:

> Looks great guys, just put it to the test. One little request would be to limit the image size pulled from the OpenGraph data (or perhaps even give a choice). I just did a test and the site I pulled in had a HUGE image set as OpenGraph.

We really have to introduce some consistency here. Maybe even return to the idea of caching images in the Media Library.

**Comment by khromov** [comment]
@ideag A pretty big issue altogether, we're probably gonna need to filter these out from the gallery view so it doesn't get cluttered with these temporary OG images. We'd also need to clean things up as images and links are added/disappeared. (Like a cron job that checks for "stale" images no longer associated with any links..)

I do think this is a great idea in the long run. Being able to create image sizes for these thumbnails and then let WP resize them would be super neat and open up for different skin layouts.

**Comment by ideag** [comment]
in a short term, setting `max-width` for the content card (also see #43) would at least make sure, large images do not break design.

**Comment by ideag** [comment]
So I've been playing around with image caching in media library in [feature-image-cache](/ideag/content-cards/tree/feature-image-cache) branch. So far, it can store the image in media library, and I was able to hide all traces of the cached images from media library - that was quite challenging and relies on a couple of pretty ugly hacks that might be high maintenance. Problem is, media library lacks some proper filters for item counts in the list view. But it was fun figuring out. 
I still need to get the cleanup done. I am thinking to do it once a day, and also to be triggered by pageviews (kind of the same way I schedule OG data rechecks).

**Comment by ideag** [comment]
Added image and link cleanup methods.
