### ISSUE TITLE
Bug with non-absolute image paths

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#41]
To reproduce:

Embed the following URL via shortcode:
http://www.dramaten.se/Repertoar/Beckomberga/

Result: The image is broken and links to:
`/Global/Repertoar/Beckomberga/BOB_lans_P_940X608b.jpg`

Here is that meta property:

``` html
<meta property="og:image" content="/Global/Repertoar/Beckomberga/BOB_lans_P_940X608b.jpg" />
```

If we find a non-absolute path, we need to prepend the domain to it.

**Comment by ideag** [comment]
Probably a case for using `filter_var($url, FILTER_VALIDATE_URL)`?
