### ISSUE TITLE
Controlling og:description length

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#42]
Saw some site with huge OG descriptions.
Would be great if we could have something like:

_Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed enim augue, ullamcorper sed ornare vitae, porta vitae odio. Quisque porttitor ut ipsum id ornare. Praesent urna ipsum..._ **(250 more words)**

The setting could be controllable through the options page?

**Comment by ideag** [comment]
@khromov What should the default limit be? 50 words?

**Comment by khromov** [comment]
@ideag 55 is the default excerpt length in WP, maybe start with that?
https://codex.wordpress.org/Plugin_API/Filter_Reference/excerpt_length

**Comment by ideag** [comment]
Thought the same.
