### ISSUE TITLE
Add max number of links processed per batch and add a weekly schedule

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#45]
We're going to be rolling this out on a WP network where thousands of content cards will be inserted, processing all of them every day would take a really long time. So I suggest we set a max number of links to be checked every time the cron job runs, something like 30 (can be user configurable).

A "Weekly" schedule would also be nice.

Finally, if the OG is working fine, but on the next check-up, the site is down, we still keep the old data, right @ideag ?

**Comment by ideag** [comment]
The way it is done at the moment, a lot of small jobs are scheduled rather than one big one, so scaling should not be a problem. And yes, OG data is updated only on successful rescan.

**Comment by khromov** [comment]
@ideag But what will happen if a user has 1000 links and checks them hourly? If each URL takes 2 seconds (a conservative estimate), the CRON just for Content Cards will take over 33 minutes to finish..

Wouldn't it make sense to limit at least how many Content Cards get updated in each CRON invocation? 

We could take some inspiration from how Broken Link Checker does this. It defaults to re-checking links every 72 hours and has some interesting approaches to background checking:

https://wordpress.org/plugins/broken-link-checker/

![screen shot 2015-09-03 at 12 07 47](https://cloud.githubusercontent.com/assets/1207507/9655849/73ddd1d8-5234-11e5-9fb3-b15c2e78b8de.png)

**Comment by ideag** [comment]
It would not be a single cron task running for 30 minutes, it would be many different cron tasks, running at different times and only updating one link's OG at a time. Also, update tasks are only scheduled for links that were recently accessed. If the link is sitting on a page that is not getting pageviews, it will not be updated. See the code here: https://github.com/ideag/content-cards/blob/master/content-cards.php#L436

**Comment by khromov** [comment]
@ideag They would be separate tasks, but internally WP CRON just loops over all jobs and does them one after the other:
https://github.com/WordPress/WordPress/blob/master/wp-cron.php#L95

So, if you have not triggered CRON for one hour, then the next CRON invocation would keep running for 30 minutes.

I really like the solution with enqueueing meta refreshes if a post gets views only. Maybe this won't be such a big problem. :+1:

**Comment by ideag** [comment]
Well, if your site gets not enough traffic to trigger cron more often, there won't be enough traffic to get many updates requests scheduled in the first place, wouldn't it?

**Comment by ideag** [comment]
I am closing this as invalid for now, we could reopen if actual performance issues arise.
