### ISSUE TITLE
Encoding issues for cached image filename

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#57]
There seems to be some encoding issues if the cached filename contains special characters, try embedding this link:
http://www.aftonbladet.se/nyheter/article21396018.ab

The result in a 404 image:
http://site.dev/wp-content/uploads/2015/09/BEDR%C3%84GERI.jpg

However, the og:image is correctly placed:
http://gfx.aftonbladet-cdn.se/image/21396163/300/imageColumn/ffa13d83b9807/BEDR%C3%84GERI.JPG

**Comment by ideag** [comment]
OK, I am going to add some sanitization to image title.
