### ISSUE TITLE
WP Site Images displaying too large next to site names

### ISSUE THREAD

**Issue by lincourtl** [ideag/content-cards#59]
Wow, this plugin has come so far in so short a time! Thanks for all your work on Content Cards. I can't believe nobody hasn't done this before now.

Just a note that it seems the new WordPress site images are being shown at too large a size next to content_cards_site_name.

You can see an example here: http://leolincourt.com/cc-card-demo/

The regular news sites, and the one WP site which isn't using the new site images, display at icon size. Meanwhile the two WP sites using the new site images are being displayed too large.

```
<div class="content_cards_site_name">
  <img scale="0" src="//subpanda.com/wp-content/uploads/2015/03/62881.png.jpg" alt="Subsequent Panda Creation" class="content_cards_favicon">
  Subsequent Panda Creation
</div>
```

**Comment by khromov** [comment]
Thanks for the bug report @lincourtl 

It looks like you are running a CSS minifier. During an update we added some additional styles but it looks like your minified CSS doesn't include them. Can you try clearing the cache in your minifier? That might solve your issues!

**Comment by lincourtl** [comment]
Derp! :bomb: 

Good catch. Sorry for the boneheaded bug report.

**Comment by khromov** [comment]
No worries @lincourtl !

Let us know if you find any further :bug:  :beetle:  

 :-)
