### ISSUE TITLE
Why does one url work but another one doesn't?

### ISSUE THREAD

**Issue by JulieH1958** [ideag/content-cards#68]
I used the following shortcodes with Content Cards. The first one embeds with no problem but the second is invalid. Can you decipher the reason why one would work but not the other? It's an https website: https//:ncmountains.net

[contentcards url="http://www.edinarealty.com/marc-cutter-realtor/homes-for-sale/707-River-Street-Taylors-Falls-MN-55084-154138266"]
[contentcards url="http://www.navicamls.net/displays/?n=253&i=1765214&k=2yff"]

Thx!

**Comment by ideag** [comment]
Hi, @JulieH1958 ! The website in second link does not have OpenGraph data set up, so Content Cards is unable to gather information required to display a proper card. 

Arūnas

**Comment by JulieH1958** [comment]
Good to know! Thank you so much, Julie
