### ISSUE TITLE
Ability to not cache images locally

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#70]
As per:
https://wordpress.org/support/topic/legal-worries?replies=1

**Comment by ideag** [comment]
This is already in master.

**Comment by khromov** [comment]
Great :+1:

**Comment by kai17** [comment]
I'm probably being a bit stupid here: I would rather not cache images locally because I'm afraid of lawyers, but I cannot find a setting to suppress caching. Am I missing something?

**Comment by ideag** [comment]
@kai17 we just released a new version on WordPress.org that includes a setting to suppress caching. It has been in the master branch of this repository for a couple weeks, but we wanted to bundle some more changes together before we released it as a new version.

**Comment by kai17** [comment]
Thank you so much! I've already installed the new version, and it seems to be working like a charm. Thank you again for this great plugin!
