### ISSUE TITLE
Doesn't work with "umlaute" (in german)

### ISSUE THREAD

**Issue by larsik78** [ideag/content-cards#77]
Hi,

obviously your plugin can't handle german sites with umlaute in the headlines. It stopps to read the headlines exactly at the umlaut.

That should be easy to fix, shouldn't it?

THANK YOU!

**Comment by khromov** [comment]
Hi @larsik78 ! 

We try to support many encodings. Could you send over a link that shows the problem? Thanks!

**Comment by larsik78** [comment]
Hi,

you cann see the error here: 
http://praesidentschaftswahlen.de/new-hampshire-in-a-nutshell/

But indeed the error occurs only in case of www.spiegel.de  - the link 
from sueddeutsche.de works fine.

Regards.

Lars

Am 2016-02-10 16:45, schrieb Stanislav Khromov:

> Hi @larsik78 [1] !
> 
> We try to support many encodings. Could you send over a link that
> shows the problem? Thanks!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/larsik78
> [2] 
> https://github.com/ideag/content-cards/issues/77#issuecomment-182436896

## 

---

Lars Kreiseler

fon: +49 (172) 79 68 195
mail: lars@cookhouseculture.de

c/o cookhouse culture GbR
karlstraße. 28

06844 dessau
fax: 0340.2211953
kontakt@cookhouseculture.de

**Comment by khromov** [comment]
@larsik78 Thanks! We'll have a look shortly and get back to you.

**Comment by ideag** [comment]
@larsik78 version 0.9.5 was released to WordPress.org a few hours ago. It fixes the Spiegel.de issue and should help with some ther non-utf8 websites, too. Let us know if you still have issues.

**Comment by larsik78** [comment]
Great. Now it works perfect!

Thank you!

Am 11.02.2016 um 16:02 schrieb Arūnas Liuiza:

> @larsik78 https://github.com/larsik78 version 0.9.5 was released to 
> WordPress.org a few hours ago. It fixes the Spiegel.de issue and 
> should help with some ther non-utf8 websites, too. Let us know if you 
> still have issues.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ideag/content-cards/issues/77#issuecomment-182899260.

## 

---

Lars Kreiseler

fon: +49 (172) 79 68 195
mail: lars@cookhouseculture.de

c/o cookhouse culture GbR
karlstraße. 28

06844 dessau
fax: 0340.2211953
kontakt@cookhouseculture.de
