### ISSUE TITLE
Are Content Cards Tagable? (ifSoHow?)

### ISSUE THREAD

**Issue by Whereisnomad** [ideag/content-cards#80]
Hello! I was wondering if it's possible to categorize a content card by tags so a user could pull up all cards under whatever category tag they may be interested in? 

Thank you!

Damon K.

**Comment by khromov** [comment]
@Whereisnomad It's not currently possible to tag content cards. This might change at some point in the future (will probably require that content cards are a CPT), but unfortunately no plans for that now. 

Thank you for the request, we'll definitely keep it in mind.
