### ISSUE TITLE
Optimize rendering on AMP pages

### ISSUE THREAD

**Issue by preslavrachev** [ideag/content-cards#82]
Great work on the plugin! There is one thing that bothers me a bit though. I've recently installed the [AMP plugin](https://wordpress.org/plugins/amp/) and since the AMP standard features a very limited subset of HTML/CSS, cards look suboptimal on my AMP pages. 

*Normal rendering*
![screenshot](https://cloud.githubusercontent.com/assets/86060/21561764/6ae271fa-ce71-11e6-8486-e96cc64b3311.png)

*With AMP-restrictions turned on*
![screenshot](https://cloud.githubusercontent.com/assets/86060/21561765/6c7d3bf8-ce71-11e6-9fcd-33fdbd908f4f.png)

I am raising this issue, looking for an advice, and potentially hoping to help you guys solve this issue. I think that eventually, card layout should simply fall back to a Blockquote style, similar to how Embedly cards get displayed, when JavaScript gets turned off

**Comment by khromov** [comment]
Good suggestion, will look into it. Thanks!

**Comment by ideag** [comment]
Basically, AMP ignores our stylesheet, because it only looks for styles within a `<style amp-custom>` tag in the `<head>` of the document. We could probably just print the content of our stylesheet into a  `<style amp-custom>`. It's not like we have very heavy styling or anything.

**Comment by preslavrachev** [comment]
@ideag @khromov Just installed a copy of the plugin directly off `master`. Based on some short-time testing, AMP-rendering looks really well. Good job, guys! I assume the changes are officially coming into the next release.

**Comment by ideag** [comment]
Thanks for testing that out. And yes, it will go into the next release. And the release will happen as soon as @khromov builds #93 :p
