### ISSUE TITLE
Allow for choosing a custom theme in the shortcode

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#85]
A possible solution for: https://wordpress.org/support/topic/how-to-clone-this-plugin-to-have-2-of-them-installed-simultaneously/

**Comment by ideag** [comment]
started the work at `fix-85-custom-themes-per-shortcode` branch. Added a shortcode argument and loaded the correct template. But I ran into a problem with css - it gets loaded way before any shortcode processing, so there is no way to know which skin css should be loaded. And we can't load them all.

Currently I do not have a good idea how to fix this.

**Comment by ideag** [comment]
We could add an option to load additional skin styles in options, but that would mean we have to be quite a bit more careful and specific in skin css.

**Comment by khromov** [comment]
I'm not a fan of this idea. Skins are for making sure the content cards look good on **your** site, not to theme them differently depending on which site you are embedding. Per-card CSS also sounds unnecessarily complex to implement.

I propose we add a class to `the_cc_css_classes()` that includes the website domain, ie for `example.com/foobar` the class would be `cc-domain-example-com`. Then the user can style it however he wants himself with external CSS.

Thoughts?

**Comment by ideag** [comment]
Hmm, I can understand the use case where people might want to differentiate the look of certain embeds. Of course, there is a case to be made, that if you need this, you can build it into your custom skin.

**Comment by ideag** [comment]
I took your advice and added a domain based class to the cards ( `"content_cards_domain_{$domain}"`, for example `content_cards_domain_wptavern-com` )
