### ISSUE TITLE
List of popular non oEmbed websites

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#9]
A default list of popular sites not currently having native oEmbed support in WP.

**Comment by khromov** [comment]
Guess we should start compiling a list.. but I'm not sure what the criteria for each site should be, any ideas @ideag ? :)

**Comment by ideag** [comment]
Not really. Actually, I am thinking of keeping the default White List very limited. There is no point of adding a lot of oEmbed patterns, because every user will need just a few of them. I don't think it is possible to create a _one size fits all_ type of list here. So maybe we should just leave `wordpress.org` and `wptavern.com` there as examples, and allow users to build their own list? What do you think, @khromov ?

**Comment by khromov** [comment]
Agree 100%, let's keep it the way it is @ideag

**Comment by ideag** [comment]
Ok, so I am closing this.
