### ISSUE TITLE
On PHP Version 7.0.28 the plugin tries to get property of non-object which results in an error

### ISSUE THREAD

**Issue by emanuelst** [ideag/content-cards#99]
On PHP Version 7.0.28 the plugin tries to get property of non-object which results in an error:

> Notice: Trying to get property of non-object in …/wp-content/plugins/content-cards/content-cards.php on line 724

This results in the media grid not loading properly.

**Comment by ideag** [comment]
Hi @emanuelst. and thanks for contributing! It is very much appreciated. This looks nice and clean, so I am going to merge it. I plan a bigger release (a new OpenGraph parser, maybe Gutenberg support) very soon, so I'll add this as a part of that. Thanks again!
